<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WinCCDashboard.Web</RootNamespace>
    <AssemblyName>WinCCDashboard.Web</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinCCDashboard.Application\WinCCDashboard.Application.csproj" />
    <ProjectReference Include="..\WinCCDashboard.Infrastructure\WinCCDashboard.Infrastructure.csproj" />
  </ItemGroup>

</Project>